name: CI Pipeline & Docker Build

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Ambil Kode
    - name: Checkout Code
      uses: actions/checkout@v4

    # Setup Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    # Install MLflow & Dependencies
    - name: Install dependencies
      run: |
        pip install mlflow==2.19.0 pandas scikit-learn numpy virtualenv seaborn matplotlib

    # Login ke Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Jalankan MLProject 
    - name: Run MLflow Project
      id: run_mlflow
      run: |
        cd MLProject
        # Jalankan script training
        python modelling.py
        
        # AMBIL RUN ID DARI FILE
        if [ -f "run_id.txt" ]; then
          RUN_ID=$(cat run_id.txt)
          echo "Detected Run ID from file: $RUN_ID"
        else
          # Fallback jika file tidak ada (Metode LS)
          echo "Warning: run_id.txt not found, using fallback..."
          RUN_ID=$(ls -td mlruns/0/*/ | head -1 | cut -d'/' -f3)
        fi
        
        # Simpan ke Environment Github Actions
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    # 6. Simpan Artefak ke GitHub 
    - name: Upload MLflow Runs
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-runs
        path: MLProject/mlruns/

    # 7. Build Docker Image 
    - name: Build Docker Image using MLflow
      run: |
        cd MLProject
        mlflow models build-docker \
          -m "runs:/$RUN_ID/model" \
          -n "${{ secrets.DOCKER_USERNAME }}/workflow-ci:latest" \
          --enable-mlserver

    # 8. Push ke Docker Hub 
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/workflow-ci:latest