name: CI Pipeline & Docker Build

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        pip install mlflow==2.19.0 pandas scikit-learn numpy virtualenv seaborn matplotlib

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Run MLflow Project
      id: run_mlflow
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: |
        cd MLProject
        
        # Jalankan dengan experiment name yang konsisten
        mlflow run . --env-manager=local --experiment-name CI_Experiment
        
        # Logika mencari Run ID
        if [ -f "run_id.txt" ]; then
          RUN_ID=$(cat run_id.txt)
        else
          # Fallback: Cari run terakhir dari mlruns lokal (biasanya meta data tersisa di sini)
          # Atau kita paksa ambil dari output mlflow run jika memungkinkan, tapi cara ini paling aman utk skrg
          RUN_ID=$(ls -td mlruns/*/*/ | head -1 | xargs basename)
        fi
        
        echo "Found Run ID: $RUN_ID"
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    - name: Build Docker Image using MLflow
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: |
        cd MLProject
        echo "Building Docker for Run ID: $RUN_ID from Remote Tracking Server..."
        
        mlflow models build-docker \
          -m "runs:/$RUN_ID/model" \
          -n "${{ secrets.DOCKER_USERNAME }}/workflow-ci:latest"

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/workflow-ci:latest