name: CI Pipeline & Docker Build

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Ambil Kode
    - name: Checkout Code
      uses: actions/checkout@v4

    # Setup Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    # Install MLflow & Dependencies
    - name: Install dependencies
      run: |
        pip install mlflow==2.19.0 pandas scikit-learn numpy virtualenv seaborn matplotlib

    # Login ke Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Jalankan MLProject 
    - name: Run MLflow Project
      id: run_mlflow
      run: |
        cd MLProject
        # Jalankan script training
        python modelling.py
        
        if [ -f "run_id.txt" ]; then
          RUN_ID=$(cat run_id.txt)
          echo "Found Run ID from file: $RUN_ID"
        else
          echo "run_id.txt not found. Searching in mlruns folder..."
          # Cari folder terbaru di DALAM subfolder apapun di mlruns (mlruns/0/xxx atau mlruns/1/xxx)
          # ls -td mengurutkan berdasarkan waktu (terbaru diatas)
          RUN_ID=$(ls -td mlruns/*/*/ | head -1 | xargs basename)
          echo "Fallback found Run ID: $RUN_ID"
        fi
        
        # Cek apakah RUN_ID masih kosong
        if [ -z "$RUN_ID" ]; then
          echo "ERROR: Could not determine Run ID."
          exit 1
        fi
        
        # Simpan ke Environment Github Actions
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    # Simpan Artefak ke GitHub 
    - name: Upload MLflow Runs
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-runs
        path: MLProject/mlruns/

    # Build Docker Image 
    - name: Build Docker Image using MLflow
      run: |
        cd MLProject
        mlflow models build-docker \
          -m "runs:/$RUN_ID/model" \
          -n "${{ secrets.DOCKER_USERNAME }}/workflow-ci:latest" \
          --enable-mlserver

    # Push ke Docker Hub 
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/workflow-ci:latest